markdown: kramdown
title: Bellese Research Guide
description: How to plan, conduct, and manage research at Bellese.
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- README.md
- go

permalink: pretty
highlighter: rouge
kramdown:
  auto_ids: true

# Author/Organization info to be displayed in the templates
author:
  name: Bellese Research Guild
  url: https://bellese.github.io/guild-design-research/

github:
  organization: Bellese
  repository: guild-design-research
  default_branch: master

collections:
  pages:
    output: true
    permalink: /:path/

generate_nodes: true
flat_namespace: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

repos:
- name: Bellese Research Guide
  description: Main repository
  url: https://github.com/Bellese/guild-design-research